# Generated by Django 5.1.1 on 2024-10-13 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expectation',
            table='demo1_expectations',
        ),
    ]
